"""Render a minimap PNG from a replay's terrain grid (full backend only).

The full ``mgz`` parser exposes ``match.map.tiles`` — the actual terrain grid — and
located starting objects. We colour each tile by its terrain (colours come from the
bundled ``terrain.json``, regenerated by ``aoe2coach update-data``) and mark each
player's Town Center, producing a recognizable minimap for the report.

Requires the optional ``viz`` extra (Pillow):  pip install -e ".[full,viz]"
"""

from __future__ import annotations

from pathlib import Path

from . import civdata

# Player slot colours (DE palette order), for the start markers.
_PLAYER_COLORS = [
    (60, 110, 255),
    (230, 50, 50),
    (60, 200, 60),
    (240, 230, 60),
    (40, 200, 230),
    (240, 130, 230),
    (130, 130, 130),
    (245, 140, 40),
]


def _hex_to_rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def _terrain_colors() -> dict[int, tuple[int, int, int]]:
    out: dict[int, tuple[int, int, int]] = {}
    for tid, info in civdata.terrain_table().items():
        colors = (info or {}).get("colors") or {}
        hexv = colors.get("level") or colors.get("up") or colors.get("down")
        if hexv:
            try:
                out[int(tid)] = _hex_to_rgb(hexv)
            except (ValueError, IndexError):
                continue
    return out


def render_minimap(replay_path: str | Path, out_path: str | Path, scale: int = 4) -> Path:
    """Render ``replay_path``'s map to a PNG at ``out_path``. Returns the path.

    Raises:
        ImportError: Pillow not installed (the ``viz`` extra).
        ValueError: not parseable by the full backend (wrong patch), or no tiles.
    """
    try:
        from PIL import Image, ImageDraw
    except ImportError as exc:  # pragma: no cover
        raise ImportError('Minimap rendering needs Pillow:  pip install -e ".[full,viz]"') from exc

    try:
        from mgz import model
    except ImportError as exc:
        raise ValueError('Minimap needs the full backend:  pip install -e ".[full]"') from exc

    with Path(replay_path).open("rb") as handle:
        match = model.parse_match(handle)

    tiles = getattr(match.map, "tiles", None)
    dim = getattr(match.map, "dimension", None)
    if not tiles or not dim:
        raise ValueError("No terrain grid in this replay (need the full backend on a ≤v66 replay).")

    palette = _terrain_colors()
    default = (30, 30, 30)
    img = Image.new("RGB", (dim, dim), default)
    px = img.load()
    for t in tiles:
        x = int(t.position.x)
        y = int(t.position.y)
        if 0 <= x < dim and 0 <= y < dim:
            px[x, y] = palette.get(t.terrain, default)

    # Upscale (nearest-neighbour) so it's viewable, then mark Town Centers.
    img = img.resize((dim * scale, dim * scale), Image.NEAREST)
    draw = ImageDraw.Draw(img)
    for p in match.players:
        tc = next((o for o in (p.objects or []) if o.name == "Town Center"), None)
        if tc is None:
            continue
        cx, cy = int(tc.position.x * scale), int(tc.position.y * scale)
        color = _PLAYER_COLORS[(p.color_id or 0) % len(_PLAYER_COLORS)]
        r = max(3, scale)
        draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=color, outline=(255, 255, 255))

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    img.save(out_path)
    return out_path
