"""Render a minimap PNG from a replay's terrain grid (full backend only).

The full ``mgz`` parser exposes ``match.map.tiles`` — the actual terrain grid — and
located starting objects. We colour each tile by its terrain (colours come from the
bundled ``terrain.json``, regenerated by ``aoe2coach update-data``) and overlay useful
markers: player Town Centers, nearby resources, relics, and a small legend. Fight
locations are not marked yet because the current deterministic battle signal is
time-based object loss, not map-position reconstruction.

Requires the optional ``viz`` extra (Pillow):  pip install -e ".[full,viz]"
"""

from __future__ import annotations

from pathlib import Path

from . import civdata

# Player slot colours (DE palette order), for the start markers.
_PLAYER_COLORS = [
    (60, 110, 255),
    (230, 50, 50),
    (60, 200, 60),
    (240, 230, 60),
    (40, 200, 230),
    (240, 130, 230),
    (130, 130, 130),
    (245, 140, 40),
]

_RESOURCE_COLORS = {
    "gold": (245, 196, 66),
    "stone": (176, 184, 196),
    "berries": (210, 80, 150),
    "herdable": (250, 245, 210),
    "hunt": (170, 115, 55),
    "relic": (255, 255, 255),
}


def _hex_to_rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def _terrain_colors() -> dict[int, tuple[int, int, int]]:
    out: dict[int, tuple[int, int, int]] = {}
    for tid, info in civdata.terrain_table().items():
        colors = (info or {}).get("colors") or {}
        hexv = colors.get("level") or colors.get("up") or colors.get("down")
        if hexv:
            try:
                out[int(tid)] = _hex_to_rgb(hexv)
            except (ValueError, IndexError):
                continue
    return out


def _classify_object(name: str | None) -> str | None:
    if not name:
        return None
    low = name.lower()
    if "town center" in low:
        return "town_center"
    if "gold" in low:
        return "gold"
    if "stone" in low:
        return "stone"
    if any(term in low for term in ("forage", "berry", "fruit bush")):
        return "berries"
    if any(term in low for term in ("sheep", "goat", "llama", "cow", "turkey", "pig")):
        return "herdable"
    if any(term in low for term in ("boar", "deer", "rhino", "elephant", "zebra", "ostrich")):
        return "hunt"
    if "relic" in low:
        return "relic"
    return None


def _xy(obj) -> tuple[float, float] | None:
    pos = getattr(obj, "position", None)
    if pos is None:
        return None
    try:
        return float(pos.x), float(pos.y)
    except (TypeError, ValueError, AttributeError):
        return None


def _draw_dot(draw, x: int, y: int, radius: int, fill, outline=(20, 20, 20)) -> None:
    draw.ellipse([x - radius, y - radius, x + radius, y + radius], fill=fill, outline=outline)


def _draw_legend(draw, scale: int) -> None:
    x, y = 8, 8
    row_h = max(12, scale * 4)
    labels = [
        ("TC", (255, 255, 255)),
        ("gold", _RESOURCE_COLORS["gold"]),
        ("stone", _RESOURCE_COLORS["stone"]),
        ("berries", _RESOURCE_COLORS["berries"]),
        ("hunt", _RESOURCE_COLORS["hunt"]),
        ("relic", _RESOURCE_COLORS["relic"]),
    ]
    width = 86
    height = 12 + row_h * len(labels)
    draw.rectangle([x - 4, y - 4, x + width, y + height], fill=(0, 0, 0), outline=(255, 255, 255))
    for idx, (label, color) in enumerate(labels):
        cy = y + 8 + idx * row_h
        _draw_dot(draw, x + 6, cy, max(2, scale // 2), color)
        draw.text((x + 16, cy - 5), label, fill=(255, 255, 255))


def render_minimap(
    replay_path: str | Path,
    out_path: str | Path,
    scale: int = 4,
    *,
    markers: bool = True,
    legend: bool = True,
) -> Path:
    """Render ``replay_path``'s map to a PNG at ``out_path``. Returns the path.

    Raises:
        ImportError: Pillow not installed (the ``viz`` extra).
        ValueError: not parseable by the full backend (wrong patch), or no tiles.
    """
    try:
        from PIL import Image, ImageDraw
    except ImportError as exc:  # pragma: no cover
        raise ImportError('Minimap rendering needs Pillow:  pip install -e ".[full,viz]"') from exc

    try:
        from mgz import model
    except ImportError as exc:
        raise ValueError('Minimap needs the full backend:  pip install -e ".[full]"') from exc

    with Path(replay_path).open("rb") as handle:
        match = model.parse_match(handle)

    tiles = getattr(match.map, "tiles", None)
    dim = getattr(match.map, "dimension", None)
    if not tiles or not dim:
        raise ValueError("No terrain grid in this replay (need the full backend on a ≤v66 replay).")

    palette = _terrain_colors()
    default = (30, 30, 30)
    img = Image.new("RGB", (dim, dim), default)
    px = img.load()
    for t in tiles:
        x = int(t.position.x)
        y = int(t.position.y)
        if 0 <= x < dim and 0 <= y < dim:
            px[x, y] = palette.get(t.terrain, default)

    # Upscale (nearest-neighbour) so it's viewable, then add readable markers.
    img = img.resize((dim * scale, dim * scale), Image.NEAREST)
    draw = ImageDraw.Draw(img)
    if markers:
        town_centers = []
        resources = []
        for p in match.players:
            for obj in getattr(p, "objects", None) or []:
                pos = _xy(obj)
                kind = _classify_object(getattr(obj, "name", ""))
                if pos is None or kind is None:
                    continue
                if kind == "town_center":
                    town_centers.append((p, obj, pos))
                else:
                    resources.append((kind, pos))

        for kind, (x, y) in resources:
            cx, cy = int(x * scale), int(y * scale)
            color = _RESOURCE_COLORS.get(kind, (255, 255, 255))
            _draw_dot(draw, cx, cy, max(2, scale // 2), color)

        tc_seen: dict[int, int] = {}
        for p, _obj, (x, y) in town_centers:
            cx, cy = int(x * scale), int(y * scale)
            color = _PLAYER_COLORS[(p.color_id or 0) % len(_PLAYER_COLORS)]
            r = max(5, scale + 2)
            _draw_dot(draw, cx, cy, r, color, outline=(255, 255, 255))
            number = getattr(p, "number", 0) or 0
            tc_seen[number] = tc_seen.get(number, 0) + 1
            label = f"P{number}" + (f"-{tc_seen[number]}" if tc_seen[number] > 1 else "")
            draw.text((cx + r + 2, cy - r), label, fill=(255, 255, 255))

        if legend:
            _draw_legend(draw, scale)

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    img.save(out_path)
    return out_path
