"""Layer 4 — render metrics + coaching advice into a markdown report."""

from __future__ import annotations

import datetime as _dt
from pathlib import Path

from .metrics import ReplayMetrics


def _players_table(metrics: ReplayMetrics) -> str:
    rich = metrics.backend == "full"
    if rich:
        header = "| Player | Civ | Result | Feudal | Castle | Imperial | Vills | Idle TC | EAPM |"
        sep = "|--------|-----|--------|--------|--------|----------|-------|---------|------|"
    else:
        header = "| Player | Civ | Result | Feudal | Castle | Imperial | Cmd/min |"
        sep = "|--------|-----|--------|--------|--------|----------|---------|"
    rows = [header, sep]
    for p in metrics.players:
        lb = p.labels
        if rich:
            idle = "—" if p.estimated_idle_tc_s is None else f"{p.estimated_idle_tc_s}s"
            vills = p.villagers_queued or "—"
            eapm = p.eapm if p.eapm is not None else "—"
            rows.append(
                f"| {p.name} | {p.civilization} | {p.result} | {lb['feudal']} | "
                f"{lb['castle']} | {lb['imperial']} | {vills} | {idle} | {eapm} |"
            )
        else:
            apm = "—" if p.command_actions_per_min is None else f"{p.command_actions_per_min:g}"
            rows.append(
                f"| {p.name} | {p.civilization} | {p.result} | {lb['feudal']} | "
                f"{lb['castle']} | {lb['imperial']} | {apm} |"
            )
    return "\n".join(rows)


def _build_orders(metrics: ReplayMetrics) -> str:
    """A short build-order line per player (full backend only)."""
    lines = []
    for p in metrics.players:
        if p.build_order:
            lines.append(f"- **{p.name}:** " + " → ".join(p.build_order[:10]))
    if not lines:
        return ""
    return "**Build orders**\n\n" + "\n".join(lines) + "\n"


def _battle_timeline(metrics: ReplayMetrics) -> str:
    """A chronological engagement timeline derived from object-count drops."""
    if not metrics.battles:
        return ""
    lines = ["**Engagement timeline** _(objects lost; combat inferred from the timeseries)_", ""]
    for b in metrics.battles:
        losses = ", ".join(f"{name} −{n}" for name, n in b["losses"].items())
        verdict = f" → **{b['trade_winner']}** won the trade" if b["trade_winner"] else " → even"
        lines.append(f"- **{b['at']}** — {losses}{verdict}")
    return "\n".join(lines) + "\n"


def build_report(metrics: ReplayMetrics, coaching: str, model: str) -> str:
    """Compose the full markdown report: facts table + build orders + Claude's coaching."""
    rated = "ranked" if metrics.rated else "unranked"
    map_label = metrics.map_name + (f" ({metrics.map_size})" if metrics.map_size else "")
    incomplete = "" if metrics.body_complete else " _(replay body was truncated)_"
    build_orders = _build_orders(metrics)
    battles = _battle_timeline(metrics)
    mid = "\n".join(s for s in (build_orders, battles) if s)
    mid_section = f"\n{mid}\n---\n" if mid else ""
    return f"""\
# AoE2 Coaching Report

**Map:** {map_label} · **Duration:** {metrics.to_dict()["duration_label"]} · \
**{rated}** · build {metrics.build} · parser: `{metrics.backend}`{incomplete}

{_players_table(metrics)}
{mid_section}
{coaching}

---

_Generated by [aoe2coach](https://github.com/kw300/aoe2coach) using {model}. Metrics are \
computed deterministically from the replay; the engagement timeline is inferred from \
object-count data (not a tactical replay); coaching is AI-generated — verify against your \
own judgment._
"""


def default_report_path(metrics: ReplayMetrics, out_dir: str | Path = "reports") -> Path:
    """A stable, readable output path derived from the replay + timestamp."""
    out_dir = Path(out_dir)
    stem = Path(metrics.source_file).stem
    safe = "".join(c if c.isalnum() or c in " -_" else "_" for c in stem).strip()[:60]
    ts = _dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    return out_dir / f"{safe or 'replay'}-{ts}.coach.md"
